import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { getHTMLTextDir } from "intlayer";
import type { NextLayoutIntlayer } from "next-intlayer";

export { generateStaticParams } from "next-intlayer";

const outfit = Outfit({
  display: "swap",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const LocaleLayout: NextLayoutIntlayer = async ({ children, params }) => {
const {locale} = await params;
  return (
    <html dir={getHTMLTextDir(locale)} lang={locale}>
      <body
        className={`${outfit.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
};

export default LocaleLayout;
